"""Output formatting for tension detection results."""

from __future__ import annotations

import re

from .detector import TensionCandidate
from .store import Tension


def format_candidates(candidates: list[TensionCandidate]) -> str:
    if not candidates:
        return "No contradictions detected."

    lines: list[str] = []
    total = len(candidates)
    for i, c in enumerate(candidates, 1):
        lines.append(f"  Tension {i}/{total}:")
        lines.append(f"    A: {c.rule_a.text}")
        lines.append(f"    B: {c.rule_b.text}")
        if c.shared_keywords:
            lines.append(f"    Keywords: {', '.join(c.shared_keywords)}")
        if c.opposing_directions:
            lines.append(f"    Directions: {', '.join(c.opposing_directions)}")
        lines.append("")
    return "\n".join(lines)


def format_tensions_for_injection(tensions: list[Tension]) -> str:
    if not tensions:
        return ""

    lines: list[str] = [
        "## Judgment Boundaries",
        "",
        "Auto-generated by tension-detect. Each pair is not a contradiction",
        "but a context-dependent switch. Check the signal to decide which applies.",
        "",
    ]
    for t in tensions:
        lines.append(f"- **{t.rule_a_text}** vs **{t.rule_b_text}**")
        lines.append(f"  - Boundary: {t.boundary}")
        lines.append(f"  - Signal: {t.signal}")
        lines.append("")
    return "\n".join(lines)


_INJECT_START = "<!-- tension-detect:start -->"
_INJECT_END = "<!-- tension-detect:end -->"


def inject_into_text(original: str, section: str) -> str:
    block = f"{_INJECT_START}\n{section}\n{_INJECT_END}"

    if _INJECT_START in original:
        pattern = re.compile(
            re.escape(_INJECT_START) + r".*?" + re.escape(_INJECT_END),
            re.DOTALL,
        )
        return pattern.sub(block, original)
    else:
        return original.rstrip() + "\n\n" + block + "\n"
